---
# tasks file for desafio_devops
- name: executa update e upgrade
  apt:
    update_cache: "yes"
    upgrade: "yes"

- name: instala os pacotes do desafio...
  apt:
    name: "{{ pacotes }}"
    state: present

- name: cria um usuario com meu nome
  user:
    name: luciano
    shell: /bin/bash
    password: "{{ senha }}"

- name: instala nginx
  apt: name=nginx state=present

- name: copia site.html
  template: src=site.html dest=/var/www/html/

- name: reinicia o servico do nginx
  systemd: name=nginx state=restarted
